version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "80:8080"
    volumes:
      - ./proxy:/etc/nginx/conf.d
    depends_on:
      - grafana
      - plant_tracker
  plant_tracker:
    build: .
  prometheus:
    build: ./prometheus
    volumes:
      - prometheus:/prometheus
  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
volumes:
  grafana:
  prometheus:
